vars:
  - top: ../..
stages:
  download:
    cmd: python3 download.py
    deps:
      - download.py
    outs:
      - ${top}/data/raw/neet-factors/:
          cache: false
          persist: false
  prepare:
    cmd: papermill prepare.ipynb ${top}/output/prepare-neet-factors.ipynb
    deps:
      - prepare.ipynb
      - ${top}/data/reference/Copy of NatCen 2023 - Administrative data on factors associated with youth NEET rates - Dataset.xlsx
    outs:
      - ${top}/data/processed/yff/neet-factors.csv:
          cache: false
          persist: false