vars:
  - top: ../..
stages:
  download-latest-monthly:
    cmd: papermill --no-progress-bar --no-report-mode get-latest-monthly-files.ipynb  ${top}/output/labour-market-latest-monthly-files.ipynb
    deps:
      - get-latest-monthly-files.ipynb
    outs:
      - ${top}/data/raw/a06-latest.xls:
          cache: false
          persist: false
      - ${top}/data/raw/unem01-latest.xls:
          cache: false
          persist: false
  process-latest-by-pcon:
    cmd: papermill --no-progress-bar --no-report-mode latest-by-pcon.ipynb ${top}/output/labour-market-latest-by-pcon.ipynb
    deps:
      - latest-by-pcon.ipynb
      - ${top}/data/raw/LMS_latest_by_geo.csv
    outs:
      - ${top}/data/processed/labour-market/latest_by_pcon_2010.csv:
          cache: false
          persist: false
  process-latest-a06:
    cmd: papermill --no-progress-bar --no-report-mode process-a06.ipynb ${top}/output/labour-market-a06.ipynb
    deps:
      - process-a06.ipynb
      - ${top}/data/raw/a06-latest.xls
    outs:
      - ${top}/data/processed/labour-market/a06.csv:
          cache: false
          persist: true
      - ${top}/data/metadata/labour-market/a06-codes.csv:
          cache: false
          persist: true