vars:
  - top: ../..
stages:
  download-from-nomis:
    cmd: python download-from-nomis-api.py
    deps:
      - download-from-nomis-api.py
    outs:
      - ${top}/data/raw/lfs_by_pcon.csv:
          cache: false
  process-latest-by-pcon:
    cmd: papermill --no-progress-bar --no-report-mode latest-by-pcon.ipynb ${top}/output/labour-market-latest-by-pcon.ipynb
    deps:
      - latest-by-pcon.ipynb
      - ${top}/data/raw/lfs_by_pcon.csv
    outs:
      - ${top}/data/processed/labour-market/most_recent_by_pcon_2010.csv:
          cache: false
          persist: false
