vars:
  - top: ../..
stages:
  process-census:
    cmd: papermill process-census.ipynb ${top}/output/process-census.ipynb
    deps:
      - process-census.ipynb
      - ${top}/data/raw/census-employment.csv
    outs:
      - ${top}/data/processed/census/employment-status.csv:
          cache: false
